### PR TITLE
Created article list page by Tag

### PR DESCRIPTION
**Pull request by ian-walker**

### CODE REVIEW

**Comment by jacqui** [comment]
I wrapped up the work in this PR - we now have tags listed below each article with tag-specific pages at `/tags/{slug}`

**Comment by TylerFisher** [comment]
I think maybe you didn't push?

**Comment by jacqui** [comment]
Oh... this is weird. I am willing to bet it has something to do with macs being insensitive?

Screen Shot 2020-08-18 at 10 10 35 am

I noticed that this branch had a leading capital letter, which was a little unexpected, but I didn't realize that my changes weren't making it to this PR. I'll try to figure it out...

**Comment by jacqui** [comment]
I couldn't figure out the casing issues with the branch name, so I've made a new PR that incorporates my work and Ian's: PR #76 

Closing this one.

**Pull request closed without merging**
