### PR TITLE
tinycms nav builder, public-facing new centered nav

### LINKED ISSUE #1022: Navigation redesign
Both members who have been building out full sites have asked for the ability to put more than just categories in the nav (e.g. about page links). It's clear this is something we're gonna have to build. I think it probably looks something like this:

- Site metadata has a `nav` array that is a list of links. Probably looks something like this:
```
[
  { "label": "News", "target": "/categories/news" },
  { "label": "About", "target": "/about" },
  ...
]
```
We could also get a little fancier and let people add sections or dropdowns or something. Not sure we want to encourage people to go too crazy on their nav though.
- We redesign the nav to center the logo/make it bigger and allow more space for more links in a second row below it. See [Block Club Chicago](https://blockclubchicago.org/) as an example. Unfortunately this means we'll have to do some sort of flyout nav as a mobile solution.
- The TinyCMS has a nav builder page where you can put in your list of links and see a live preview of the nav. In the builder, you can select from your list of categories, tags, authors and static pages. This saves to the site metadata nav object.

### PR DESCRIPTION
**Pull request by jacqui**
Closes #1022 

This PR adds a nav builder to the tinycms:

1. nav must have at least one link
2. nav cannot include duplicate links
3. links can be removed one at a time by clicking on each one
4. all links can be removed at once by clicking the "clear" button
5. links can be reordered via drag & drop (npm `react-beautiful-dnd`)
6. tinycms homepage now includes a link to get to this new tool

This page can be accessed at `/tinycms/nav` and linked from the tinycms homepage. 

Nav config is read from and stored in the site metadata JSON at the top level key `nav` and links are generated based on each type (author, category, static page or tag) from a utils function.

Saving the nav operates similarly to saving the site settings, in that successful updates will trigger a site rebuild.

This PR also updates the `GlobalNav` component to display the nav-builder-configured links in a centered line below the centered site logo. The donate button should appear at the very top right. @TylerFisher I struggled laying all of this out and, with thanks & apologies, hope you can make this right 🙏 

This PR also includes some small but long-needed improvements to the tinycms notification component, fixing the width, padding and adding ability to dismiss the alert. 

Finally, I was able to fix up the UI/UX issues originally happening when dragging and dropping a table row by applying the right display attributes depending on the interaction status.

### CODE REVIEW

**Comment by TylerFisher** [comment]
Nice! I like this. A few things:

1. You can't add the first item in the select without selecting something else first. There should probably be a "--- Please select ---" or something at the top so this doesn't get in the way.
2. There needs to be a way to remove one thing without clearing the whole thing.
3. I don't think links should be able to be duplicated.

I like keeping this as a separate page. The settings page is overloaded at this point. So I think it gets its own listing on the tinycms homepage and the admin nav.

**Comment by TylerFisher** [comment]
One small thing: Can the labels for the ordering not be zero-indexed? Otherwise, this is good.

**Comment by jacqui** [comment]
> One small thing: Can the labels for the ordering not be zero-indexed? Otherwise, this is good.

Good point - I meant to do that index fix and forgot! The rows are now numbered starting with `1` instead of `0` :)

**Comment by TylerFisher** [comment]
Updated this with the ability to add custom links and preview the nav in the builder

**Pull request merged**
