### PR TITLE
Feature/review newsletter archives

### LINKED ISSUE #1186: Release newsletter archives feature

### PR DESCRIPTION
**Pull request by jacqui**
Closes #1186 

This updates the newsletter archives feature:

* now uses a new embed component `<LetterheadNewsletter>` 
* saves `emailTemplate` markup in the `newsletter_editions.content` in Hasura
* now uses the newsletter subheadline in the article stream for the newsletter index

Relies on https://github.com/news-catalyst/hasura/pull/113 which must be run in production Hasura. The `npm run build:newsletters` task is setup to run on every build in staging-tiny-news-sites, but must be added to the production Vercel settings as well.

### CODE REVIEW

**Comment by TylerFisher** [comment]
We have some exposed secrets in this PR we should clean up. Also, I think the newsletter editions need publish dates. Looks like that's available as `newsletter_published_at`. With those, we'd want those on the edition pages themselves and on the index page, sorting newsletter editions in a reverse chron feed.

**Comment by TylerFisher** [comment]
Also getting some build errors
Screen Shot 2022-04-14 at 4 04 40 PM

**Comment by jacqui** [comment]
> We have some exposed secrets in this PR we should clean up. Also, I think the newsletter editions need publish dates. Looks like that's available as `newsletter_published_at`. With those, we'd want those on the edition pages themselves and on the index page, sorting newsletter editions in a reverse chron feed.

Oops! I did not mean to check that settings script in, I'll fix that right away. And yes, you're right about the published date, it's already being stored in the database table for this content as you pointed out. I'll update the index to include these dates and sort by them, plus add to the individual newsletter edition page.

**Comment by jacqui** [comment]
Okay, this has been updated:

* I removed the secrets in script/settings.js - I didn't mean to check this file in; first, I replaced the sensitive values in the file using git filter-branch (with a bunch of Xs) and then I removed the file from the repo
* The newsletter index page is sorted by published date reverse chron/most recent at the top
* The index article stream includes the newsletter published date in each article link
* Each newsletter edition page includes the published date above the embed
* Finally, I fixed the cause of the build error occurring in angdiaryo's site

**Pull request merged**
