### PR TITLE
tinycms

### PR DESCRIPTION
**Pull request by jacqui**
_this is ready for review_

**There's a lot in the PR, but I think you've seen most of it already @TylerFisher.**

[http://localhost:3000/tinycms/homepage](http://localhost:3000/tinycms/homepage) has most of the changes. As we discussed on slack earlier, you now click a button to change the featured article; this opens a modal with search; and saving + publishing is a separate step with confirmation.

----

Related to [this issue in the tinycms repo](https://github.com/news-catalyst/tinynews-tinycms/issues/40) and a discussion on slack, we decided to move the tinycms functionality into the same repo & app as the frontend.

As part of this move, we're changing the homepage editor significantly, both simplifying it and hopefully making it nicer and more intuitive to use.

Moving the tinycms features to this repo means we need to access the admin API. Add these to your `.env.local` (full values are in slack):

```
ADMIN_CONTENT_DELIVERY_API_URL="https://##############.cloudfront.net/cms/manage/production"
ADMIN_CONTENT_DELIVERY_API_ACCESS_TOKEN="###########################################"
```

* [x] move authors list page to `/tinycms/authors`
* [x] move add author page to `/tinycms/authors/add` (_this makes me miss REST_)
* [x] move edit author page to `/tinycms/authors/[id]`
* [x] admin nav to get around authors, homepage, eventually analytics
* [ ] where does authentication get implemented? do we need login/logout within this app?
* [x] make a new homepage editor at `/tinycms/homepage`
* [x] homepage editor should render either the big featured or large package story layout just like `/` does
* [x] hp editor has click-to-edit on featured articles that displays a search form in the 'big featured story' layout
* [x] hp editor search form returns list of matching articles (big featured story layout)
* [x] hp editor search form shows loading spinner while finding search results (big featured story layout)
* [x] clicking a search result article makes that the new featured article in that spot (big featured story layout)
* [x] successfully saving & publishing new homepage layout refreshes the page (big featured story layout)
* [x] need user feedback/messaging when featuring a new article in a spot - **went with a bulma progress bar and some text**
* [x] hp editor has layout switcher (big featured, large package) that changes the page view
* [x] outline featured article spots for easier identification of clickable / editable areas (big featured story layout)
* [ ] ~hp editor lets you change featured articles in the 'large package story lead' layout~
* [x] display button instead of background colour above featured article spot
* [x] use modal for search form
* [x] confirm before saving and publishing; separate step to save & publish
* [x] display success or error message after saving/publishing

For simplicity's sake I'm going to do all the click-to-edit stuff in the currently selected HP layout, which is `BigFeaturedStory`, and then roll it out to the other layout option.

### CODE REVIEW

**Comment by jacqui** [comment]
Homepage Editor for Big Featured Story: Homepage Editor for Big Featured Story

Clicking to edit the featured spot in the homepage editor: Screen Shot 2020-09-17 at 3 55 24 pm

Switched to Large Package Story layout: Screen Shot 2020-09-17 at 3 56 09 pm

**Comment by TylerFisher** [comment]
Hm, having an issue where I don't see any stories on the page when I load the editor.

**Comment by jacqui** [comment]
> Hm, having an issue where I don't see any stories on the page when I load the editor. Looks like the queries find the most recent layout, but it looks for a story ID that doesn't exist currently. Is this a revision ID thing? We should update webiny again -- I think they've fixed that issue.

Okay yes, we should definitely upgrade webiny if that revisionID has been fixed... but I thought I coded the homepage functionality to look up stories by slugs. I'll look into this issue today and update this PR.

**Comment by jacqui** [comment]
Okay, oops - I had coded it to use the ID instead of the slug. Fixed that now, verified that the slug is being stored instead of the ID, and that the article is displayed when loading the homepage editor.

I had to fix a slightly confusing merge conflict first, but all should be good now. This is ready for review in other words :)

**Pull request closed without merging**
